# Project 2: Topic Classification

In this project, you'll work with text data from newsgroup postings on a variety of topics. You'll train classifiers to distinguish between the topics based on the text of the posts. Whereas with digit classification, the input is relatively dense: a 28x28 matrix of pixels, many of which are non-zero, here we'll represent each document with a "bag-of-words" model. As you'll see, this makes the feature representation quite sparse -- only a few words of the total vocabulary are active in any given document. The bag-of-words assumption here is that the label depends only on the words; their order is not important.

The SK-learn documentation on feature extraction will prove useful:
http://scikit-learn.org/stable/modules/feature_extraction.html

Each problem can be addressed succinctly with the included packages -- please don't add any more. Grading will be based on writing clean, commented code, along with a few short answers.

As always, you're welcome to work on the project in groups and discuss ideas on the course wall, but please prepare your own write-up and write your own code.

In [14]:
# This tells matplotlib not to try opening a new window for each plot.
%matplotlib inline

# General libraries.
import re
import numpy as np
import matplotlib.pyplot as plt

# SK-learn libraries for learning.
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.grid_search import GridSearchCV

# SK-learn libraries for evaluation.
from sklearn.metrics import confusion_matrix
from sklearn import metrics
from sklearn.metrics import classification_report

# SK-learn library for importing the newsgroup data.
from sklearn.datasets import fetch_20newsgroups

# SK-learn libraries for feature extraction from text.
from sklearn.feature_extraction.text import *

Load the data, stripping out metadata so that we learn classifiers that only use textual features. By default, newsgroups data is split into train and test sets. We further split the test so we have a dev set. Note that we specify 4 categories to use for this project. If you remove the categories argument from the fetch function, you'll get all 20 categories.

In [15]:
categories = ['alt.atheism', 'talk.religion.misc', 'comp.graphics', 'sci.space']
newsgroups_train = fetch_20newsgroups(subset='train',
                                      remove=('headers', 'footers', 'quotes'),
                                      categories=categories)
newsgroups_test = fetch_20newsgroups(subset='test',
                                     remove=('headers', 'footers', 'quotes'),
                                     categories=categories)

num_test = len(newsgroups_test.target)
test_data, test_labels = newsgroups_test.data[num_test/2:], newsgroups_test.target[num_test/2:]
dev_data, dev_labels = newsgroups_test.data[:num_test/2], newsgroups_test.target[:num_test/2]
train_data, train_labels = newsgroups_train.data, newsgroups_train.target

print 'training label shape:', train_labels.shape
print 'test label shape:', test_labels.shape
print 'dev label shape:', dev_labels.shape
print 'labels names:', newsgroups_train.target_names

training label shape: (2034,)
test label shape: (677,)
dev label shape: (676,)
labels names: ['alt.atheism', 'comp.graphics', 'sci.space', 'talk.religion.misc']


(1) For each of the first 5 training examples, print the text of the message along with the label.

[2 pts]

In [ ]:
def P1(num_examples=5):
### STUDENT START ###
    for i in range(num_examples):
        print 'Label' + str(i) + ':', train_labels[i], 
        print 'Data' + str(i) + ':' ,train_data[i]

### STUDENT END ###
P1(5)

(2) Use CountVectorizer to turn the raw training text into feature vectors. You should use the fit_transform function, which makes 2 passes through the data: first it computes the vocabulary ("fit"), second it converts the raw text into feature vectors using the vocabulary ("transform").

The vectorizer has a lot of options. To get familiar with some of them, write code to answer these questions:

a. The output of the transform (also of fit_transform) is a sparse matrix: http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.sparse.csr_matrix.html. What is the size of the vocabulary? What is the average number of non-zero features per example? What fraction of the entries in the matrix are non-zero? Hint: use "nnz" and "shape" attributes.

b. What are the 0th and last feature strings (in alphabetical order)? Hint: use the vectorizer's get_feature_names function.

c. Specify your own vocabulary with 4 words: ["atheism", "graphics", "space", "religion"]. Confirm the training vectors are appropriately shaped. Now what's the average number of non-zero features per example?

d. Instead of extracting unigram word features, use "analyzer" and "ngram_range" to extract bigram and trigram character features. What size vocabulary does this yield?

e. Use the "min_df" argument to prune words that appear in fewer than 10 documents. What size vocabulary does this yield?

f. Using the standard CountVectorizer, what fraction of the words in the dev data are missing from the vocabulary? Hint: build a vocabulary for both train and dev and look at the size of the difference.

[6 pts]

In [16]:
def P2():
### STUDENT START ###
    
    # Solution to Part A
    countVectorizer = CountVectorizer()
    train_counts_default = countVectorizer.fit_transform(train_data)
    print 'Shape of vector', train_counts_default.shape
    print 'Avg number of Non zero features: ', float(train_counts_default.nnz)/2034.0
    print 'Fraction of non zero: ', float(train_counts_default.nnz)/(26879.0*2034)
    
    #Solution to Part B
    print 'First Feature String: ',countVectorizer.get_feature_names()[0]
    print 'Last Feature String: ', countVectorizer.get_feature_names()[26878]
    
    #Solution to part C
    countVectorizer2 = CountVectorizer(vocabulary=["atheism", "graphics", "space", "religion"])
    #countVectorizer.vocabulary_ = ["atheism", "graphics", "space", "religion"]
    train_counts_custom_vocab = countVectorizer2.transform(train_data)
    print 'Shape with custom vocabulary: ', train_counts_custom_vocab.shape
    print 'Avg number of Non zero features with custom vocabulary: ',float(train_counts_custom_vocab.nnz)/2034.0

    #Solution to part D
    countVectorizer3 = CountVectorizer(analyzer='word', ngram_range=(2,2))
    train_counts_bigram = countVectorizer3.fit_transform(train_data)
    print 'Size of Vocabulary for bigram data:' , len(countVectorizer3.vocabulary_)
    
    countVectorizer4 = CountVectorizer(analyzer='word', ngram_range=(3,3))
    train_counts_trigram = countVectorizer4.fit_transform(train_data)
    print 'Size of Vocabulary for trigram data:' , len(countVectorizer4.vocabulary_)
    
    #Solution to part E
    countVectorizer5 = CountVectorizer(min_df=10)
    train_counts_min10 = countVectorizer5.fit_transform(train_data)
    print 'Size of vocab with min_df=10: ', len(countVectorizer5.vocabulary_)
    
    #Solution to Part F
    countVectorizer6 = CountVectorizer()
    train_counts_dev = countVectorizer6.fit_transform(dev_data)
    print 'Size of vocab with dev data: ', len(countVectorizer6.vocabulary_)
    print 'Number of words missing: ', len(countVectorizer.vocabulary_)-len(countVectorizer6.vocabulary_)
    
### STUDENT END ###

P2()

Shape of vector (2034, 26879)
Avg number of Non zero features:  96.7059980334
Fraction of non zero:  0.00359782722696
First Feature String:  00
Last Feature String:  zyxel
Shape with custom vocabulary:  (2034, 4)
Avg number of Non zero features with custom vocabulary:  0.268436578171
Size of Vocabulary for bigram data: 194891
Size of Vocabulary for trigram data: 315692
Size of vocab with min_df=10:  3064
Size of vocab with dev data:  16246
Number of words missing:  10633


(3) Use the default CountVectorizer options and report the f1 score (use metrics.f1_score) for a k nearest neighbors classifier; find the optimal value for k. Also fit a Multinomial Naive Bayes model and find the optimal value for alpha. Finally, fit a logistic regression model and find the optimal value for the regularization strength C using l2 regularization. A few questions:

a. Why doesn't nearest neighbors work well for this problem?

b. Any ideas why logistic regression doesn't work as well as Naive Bayes?

c. Logistic regression estimates a weight vector for each class, which you can access with the coef\_ attribute. Output the sum of the squared weight values for each class for each setting of the C parameter. Briefly explain the relationship between the sum and the value of C.

[4 pts]

In [42]:
def P3():
### STUDENT START ###
    countVectorizer_p3 = CountVectorizer()
    train_counts_default_p3 = countVectorizer_p3.fit_transform(train_data)
    #Creating Classifier
    knn_clf_p3 = KNeighborsClassifier()
    
    knn_params = {'n_neighbors':[1,5,10,25,75, 90,95,96,97,100]}
    gsv_knn = GridSearchCV(knn_clf_p3,knn_params,scoring='f1_weighted')
    gsv_knn.fit(train_counts_default_p3,train_labels)
    print "The best k value is: ", gsv_knn.best_params_
    
    
    mnb_clf_p3 = MultinomialNB()
    mnb_params = {'alpha':[0.000000000000001,0.00000000000001,0.0000000000001,0.000000000001,0.00000000001, 0.0000000001,0.0000001,0.00001,0.001,0.1,1,0]}
    gsv_mnb = GridSearchCV(mnb_clf_p3,mnb_params,scoring='f1_weighted')
    gsv_mnb.fit(train_counts_default_p3,train_labels)
    print "The best alpha value is: ", gsv_mnb.best_params_

    
    lr_params = [0.001,0.1,0.5,0.55,0.9]
    for c in lr_params:
        print c
        lr_clf_p3 = LogisticRegression(C=c) 
        model_p3 = lr_clf_p3.fit(train_counts_default_p3,train_labels)
        print sum(model_p3.coef_**2)
        
    ### STUDENT END ###
P3()

The best k value is:  {'n_neighbors': 96}
The best alpha value is:  {'alpha': 0.001}
0.001
[  1.39200027e-04   2.68304316e-04   1.74368725e-06 ...,   2.03969381e-07
   8.15877526e-07   5.92265341e-07]
<type 'numpy.ndarray'>
0.1
[  1.05552109e-02   6.88961312e-03   9.01694777e-05 ...,   2.23903943e-06
   8.95615771e-06   1.13107261e-04]
<type 'numpy.ndarray'>
0.5
[  3.39302823e-02   1.89650590e-02   7.94883799e-05 ...,   2.49287477e-06
   9.97149909e-06   3.19518231e-04]
<type 'numpy.ndarray'>
0.55
[  3.58204698e-02   2.00150109e-02   8.01261327e-05 ...,   2.50317946e-06
   1.00127178e-05   3.39720664e-04]
<type 'numpy.ndarray'>
0.9
[  4.67498671e-02   2.60492587e-02   9.17166958e-05 ...,   2.54521393e-06
   1.01808557e-05   4.49402671e-04]
<type 'numpy.ndarray'>


ANSWER:

(4) Train a logistic regression model. Find the 5 features with the largest weights for each label -- 20 features in total. Create a table with 20 rows and 4 columns that shows the weight for each of these features for each of the labels. Create the table again with bigram features. Any surprising features in this table?

[5 pts]

In [36]:
def P4():
### STUDENT START ###
    countVectorizer_p4 = CountVectorizer()
    train_counts_default_p4 = countVectorizer_p4.fit_transform(train_data)
    #print train_counts_default_p4[10,24380]
    #print countVectorizer_p4.vocabulary_
    
    lr_clf_p4 = LogisticRegression(C=0.5,)
    lr_clf_p4 =  lr_clf_p4.fit(train_counts_default_p4, train_labels)
    dev_counts_default_p4 = countVectorizer_p4.transform(dev_data)
    print 'Score:',lr_clf_p4.score(dev_counts_default_p4,dev_labels)
    model_coef = lr_clf_p4.coef_
    model_coef_sorted = np.argsort(model_coef, axis=1)
    #print model_coef_sorted.shape
    for row in range(4):
        print 'Label:', row
        temp_model = model_coef_sorted[row,-5:]
        print temp_model
        #for max_point in temp_model:
            #print train_counts_default_p4[row,max_point]
    #print model_coef_sorted[1,-5:]
    #print model_coef_sorted[2,-5:]
    #print model_coef_sorted[3,-5:]
    #for row in range(4):
        #for column in range(model_coef_sorted[0].size):
            #print model_coef_sorted[row,column]
### STUDENT END ###
P4()

Score: 0.71449704142
Label: 0
[ 7841  3866 20430  4784  3870]
Label: 1
[ 6555  1145 10376 12769 11552]
Label: 2
[22570 14540 16697 17597 22567]
Label: 3
[17609 10234  4743  5901  5904]


ANSWER:

(5) Try to improve the logistic regression classifier by passing a custom preprocessor to CountVectorizer. The preprocessing function runs on the raw text, before it is split into words by the tokenizer. Your preprocessor should try to normalize the input in various ways to improve generalization. For example, try lowercasing everything, replacing sequences of numbers with a single token, removing various other non-letter characters, and shortening long words. If you're not already familiar with regular expressions for manipulating strings, see https://docs.python.org/2/library/re.html, and re.sub() in particular. With your new preprocessor, how much did you reduce the size of the dictionary?

For reference, I was able to improve dev F1 by 2 points.

[4 pts]

In [ ]:
def empty_preprocessor(s):
    return s

def better_preprocessor(s):
### STUDENT START ###
    s= s.lower()
    s=remove_non_alpha_numeric(s)
    #s=remove_number(s)
    return s

def remove_number(s):
    s=re.sub('\s(\d)+\s',' ZZ ',s)
    return s

def remove_non_alpha_numeric(s):
    s=re.sub('([^\s\w]|_)+','',s)
    #s=re.search('(\w+|\s)',s).group(1)
    return s

print train_data[0]
print better_preprocessor(str(train_data[0]))
#print better_preprocessor(' 1234 4rf 1231 ')
### STUDENT END ###

def P5():
### STUDENT START ###
    i = 0
    countVectorizer_p5 = CountVectorizer(preprocessor=better_preprocessor)
    train_counts_default_p5 = countVectorizer_p5.fit_transform(train_data)
    
    #prep = countVectorizer_p5.build_preprocessor()
    #print str(train_data[0])
    #print prep(str(train_data[0]))
    #print better_preprocessor(str(train_data[0]))

    print len(countVectorizer_p5.vocabulary_)
    #print sorted(countVectorizer_p5.vocabulary_)
    dev_counts_default_p5 = countVectorizer_p5.transform(dev_data)
    
    lr_clf_p5 = LogisticRegression(C=0.5)
    lr_clf_p5 = lr_clf_p5.fit(train_counts_default_p5,train_labels)
    print 'Score:', lr_clf_p5.score(dev_counts_default_p5,dev_labels)
    
    
    
### STUDENT END ###
#P5()

(6) The idea of regularization is to avoid learning very large weights (which are likely to fit the training data, but not generalize well) by adding a penalty to the total size of the learned weights. That is, logistic regression seeks the set of weights that minimizes errors in the training data AND has a small size. The default regularization, L2, computes this size as the sum of the squared weights (see P3, above). L1 regularization computes this size as the sum of the absolute values of the weights. The result is that whereas L2 regularization makes all the weights relatively small, L1 regularization drives lots of the weights to 0, effectively removing unimportant features.

Train a logistic regression model using a "l1" penalty. Output the number of learned weights that are not equal to zero. How does this compare to the number of non-zero weights you get with "l2"? Now, reduce the size of the vocabulary by keeping only those features that have at least one non-zero weight and retrain a model using "l2".

Make a plot showing accuracy of the re-trained model vs. the vocabulary size you get when pruning unused features by adjusting the C parameter.

Note: The gradient descent code that trains the logistic regression model sometimes has trouble converging with extreme settings of the C parameter. Relax the convergence criteria by setting tol=.01 (the default is .0001).

[4 pts]

In [ ]:
def P6():
    # Keep this random seed here to make comparison easier.
    np.random.seed(0)

    ### STUDENT START ###

    

    ### STUDENT END ###
P6()

(7) Use the TfidfVectorizer -- how is this different from the CountVectorizer? Train a logistic regression model with C=100.

Make predictions on the dev data and show the top 3 documents where the ratio R is largest, where R is:

maximum predicted probability / predicted probability of the correct label

What kinds of mistakes is the model making? Suggest a way to address one particular issue that you see.

[4 pts]

In [ ]:
#def P7():
    ### STUDENT START ###



    ### STUDENT END ###
#P7()

ANSWER:

(8) EXTRA CREDIT

Try implementing one of your ideas based on your error analysis. Use logistic regression as your underlying model.

- [1 pt] for a reasonable attempt
- [2 pts] for improved performance